### ISSUE TITLE
cannot import name 'Card' from partially initialized module 'anki.cards'

### ISSUE THREAD

**Issue by deep-learning-newbie** [bmaupin/flashcard-sets#3]
Hi, when I used this script I got an error.  how to fix it?

user@pc:/anki$ python csv-to-apkg.py /anki/dictionary_1.csv  /anki/dictionary_1.apkg
Traceback (most recent call last):
  File "csv-to-apkg.py", line 9, in <module>
    from anki.exporting import AnkiPackageExporter
  File "/home/user/anaconda3/envs/t1/lib/python3.8/site-packages/anki/exporting.py", line 16, in <module>
    from anki import hooks
  File "/home/user/anaconda3/envs/t1/lib/python3.8/site-packages/anki/hooks.py", line 20, in <module>
    from anki.hooks_gen import *
  File "/home/user/anaconda3/envs/t1/lib/python3.8/site-packages/anki/hooks_gen.py", line 14, in <module>
    from anki.cards import Card
  File "/home/user/anaconda3/envs/t1/lib/python3.8/site-packages/anki/cards.py", line 15, in <module>
    from anki.consts import *
  File "/home/user/anaconda3/envs/t1/lib/python3.8/site-packages/anki/consts.py", line 94, in <module>
    import anki.collection
  File "/home/user/anaconda3/envs/t1/lib/python3.8/site-packages/anki/collection.py", line 44, in <module>
    import anki.latex
  File "/home/user/anaconda3/envs/t1/lib/python3.8/site-packages/anki/latex.py", line 15, in <module>
    from anki.template import TemplateRenderContext, TemplateRenderOutput
  File "/home/user/anaconda3/envs/t1/lib/python3.8/site-packages/anki/template.py", line 36, in <module>
    from anki.cards import Card
ImportError: cannot import name 'Card' from partially initialized module 'anki.cards' (most likely due to a circular import) (/home/user/anaconda3/envs/t1/lib/python3.8/site-packages/anki/cards.py)

**Comment by bmaupin** [comment]
Did you follow the step in the installation to install the anki library? https://github.com/bmaupin/flashcard-sets/tree/main/scripts#installation

It's been a while since I've used this myself. Python is notoriously bad for dependency management. This came up just a couple weeks ago on hacker news: https://news.ycombinator.com/item?id=29434740

My first guess would be that some breaking change has been made in the anki library since I wrote this. You could try to install an older version of the anki library--maybe correlate it to the version that was current when the script was written?


I don't really have time to look at this myself right now but if you know of a way I can specify version dependencies let me know.

If you're not able to get it working, another alternative is this library: https://github.com/kerrickstaley/genanki

Hope that helps!
